// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using System.Runtime.InteropServices;
using Content.Client.SS220.Experience.UiElements;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.SS220.Experience;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.SS220.Experience.Ui;

[GenerateTypedNameReferences]
public sealed partial class ExperienceViewWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private ISawmill _sawmill = default!;

    public Action<PlayerChangeSkill>? OnSubmitChangeAction;

    private Dictionary<ProtoId<SkillTreeGroupPrototype>, ExperienceSkillTreeGroupContainer> _cachedControls = new();

    private Dictionary<ProtoId<SkillTreeGroupPrototype>, List<SkillTreeView>> _data = new();

    private HashSet<ProtoId<KnowledgePrototype>> _knowledges = new();

    private int _freeSublevelPoints;
    private int _spendPoints;

    public ExperienceViewWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = Logger.GetSawmill("experience-view-window");

        SubmitButton.OnPressed += (_) => OnSubmitChangeAction?.Invoke(new PlayerChangeSkill
        {
            SkillSublevels = GetChangedSublevels()
        });

        ClearSpentPointsButton.OnPressed += OnClearSpentPointsButton;
    }

    public void SetKnowledge(HashSet<ProtoId<KnowledgePrototype>>? knowledges)
    {
        _knowledges = knowledges is null ? [] : knowledges;
        FinalizeUpdateKnowledge();
    }

    public void SetSkillDictionary(Dictionary<ProtoId<SkillTreeGroupPrototype>, List<SkillTreeView>>? data)
    {
        _data = data is null ? [] : data;
        Update();
    }

    public void SetKeyValue(ProtoId<SkillTreeGroupPrototype> key, List<SkillTreeView> skillTreeViews)
    {
        _data.Remove(key);
        _data.Add(key, skillTreeViews);

        UpdateGroupPartially(key, skillTreeViews);

        FinalizeUpdateSkillTree();
    }

    public void SetFreeSublevelPoints(int freeSublevelPoints)
    {
        _spendPoints = 0;
        _freeSublevelPoints = freeSublevelPoints;
        UpdateSublevel();
    }

    public Dictionary<ProtoId<SkillTreePrototype>, int> GetChangedSublevels()
    {
        var result = new Dictionary<ProtoId<SkillTreePrototype>, int>();

        foreach (var child in ExperienceTreeGroupsContainer.Children)
        {
            if (child is not ExperienceSkillTreeGroupContainer groupContainer)
                continue;

            foreach (var groupChild in groupContainer.SkillTreeContainer.Children)
            {
                if (groupChild is not ExperienceTreeContainer treeContainer)
                    continue;

                result.Add(treeContainer.SkillTreeId, treeContainer.SpendPoints);
            }
        }

        return result;
    }

    private void Update()
    {
        if (_data.Count == 0)
            _cachedControls.Clear();

        foreach (var (key, value) in _data)
            UpdateGroupPartially(key, value);

        FinalizeUpdateSkillTree();
        FinalizeUpdateKnowledge();
        UpdateSublevel();
    }

    private void FinalizeUpdateSkillTree()
    {
        ExperienceTreeGroupsContainer.RemoveAllChildren();

        PanelContainer? divider = null;
        foreach (var control in _cachedControls.Values.OrderBy((x) => x.Name))
        {
            divider = new PanelContainer
            {
                StyleClasses = { StyleBase.ClassLowDivider },
            };
            ExperienceTreeGroupsContainer.AddChild(control);
            ExperienceTreeGroupsContainer.AddChild(divider);
        }

        if (divider is not null)
            ExperienceTreeGroupsContainer.RemoveChild(divider);
    }

    private void FinalizeUpdateKnowledge()
    {
        knowledgesContainer.RemoveAllChildren();

        PanelContainer? divider = null;
        foreach (var knowledge in _knowledges.OrderBy((x) => x.Id))
        {
            divider = new PanelContainer
            {
                StyleClasses = { StyleBase.ClassLowDivider },
            };
            var knowledgeControl = new KnowledgeLabel();
            knowledgeControl.SetKnowledge(knowledge);
            knowledgesContainer.AddChild(knowledgeControl);
            knowledgesContainer.AddChild(divider);
        }

        if (divider is not null)
            knowledgesContainer.RemoveChild(divider);
    }

    private void UpdateGroupPartially(ProtoId<SkillTreeGroupPrototype> key, List<SkillTreeView>? skillTreeViews)
    {
        if (!_data.ContainsKey(key))
        {
            _sawmill.Error($"UI doesnt contain {key} in its data, but update was called");
            return;
        }

        if (!_prototype.Resolve(key, out var keyProto))
            return;

        if (!_cachedControls.TryGetValue(key, out var cachedControl))
        {
            cachedControl = new ExperienceSkillTreeGroupContainer();
            ExperienceTreeGroupsContainer.AddChild(cachedControl);
            _cachedControls.Add(key, cachedControl);
        }

        skillTreeViews ??= _data[key];

        cachedControl.SetGroupName(FormattedMessage.FromMarkupPermissive(Loc.GetString(keyProto.GroupName)));
        cachedControl.UpdateWithList(CollectionsMarshal.AsSpan(skillTreeViews), key);

        UpdateSublevel();
    }

    private void UpdateSublevel()
    {
        var canChange = _freeSublevelPoints > _spendPoints;

        FreePointsOptionContainer.Visible = canChange || _spendPoints > 0;
        ClearSpentPointsButton.Disabled = _spendPoints < 1;

        FreePointsShower.SetMessage(Loc.GetString("experience-view-free-sublevel-points-text", ("FreeSublevel", _freeSublevelPoints - _spendPoints)));

        foreach (var child in ExperienceTreeGroupsContainer.Children)
        {
            if (child is not ExperienceSkillTreeGroupContainer groupContainer)
                continue;

            foreach (var groupChild in groupContainer.SkillTreeContainer.Children)
            {
                if (groupChild is not ExperienceTreeContainer treeContainer)
                    continue;

                treeContainer.HaveFreePoints = canChange;
                treeContainer.SubdataContainer.Visible = treeContainer.OpenedByUser || canChange;

                // god forgive me...
                if (treeContainer.OnAddSublevelPoint is null)
                    treeContainer.OnAddSublevelPoint += OnAddSublevelPoint;
            }
        }
    }

    private void OnAddSublevelPoint()
    {
        _spendPoints++;

        UpdateSublevel();
    }

    private void OnClearSpentPointsButton(BaseButton.ButtonEventArgs args)
    {
        foreach (var child in ExperienceTreeGroupsContainer.Children)
        {
            if (child is not ExperienceSkillTreeGroupContainer groupContainer)
                continue;

            foreach (var groupChild in groupContainer.SkillTreeContainer.Children)
            {
                if (groupChild is not ExperienceTreeContainer treeContainer)
                    continue;

                treeContainer.SpendPoints = 0;
            }
        }

        _spendPoints = 0;
        UpdateSublevel();
    }
}
