// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using Content.Client.SS220.Experience.UiElements;
using Content.Client.UserInterface.Controls;
using Content.Shared.Mind;
using Content.Shared.Roles;
using Content.Shared.SS220.Experience;
using Microsoft.CodeAnalysis;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.SS220.Experience.Ui;

[GenerateTypedNameReferences]
public sealed partial class ExperienceEditorWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly ExperienceEditorSystem _experienceEditor = default!;
    private readonly ExperienceInfoSystem _experienceInfo = default!;

    private static readonly LocId NoJobName = "experience-editor-no-job-name";
    private static readonly LocId NoAntagRoleName = "experience-editor-no-antag-name";

    public ExperienceEditorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _experienceEditor = _entityManager.System<ExperienceEditorSystem>();
        _experienceInfo = _entityManager.System<ExperienceInfoSystem>();

        var metadataQuery = _entityManager.GetEntityQuery<MetaDataComponent>();
        var experienceEntities = _entityManager.EntityQueryEnumerator<ExperienceComponent>();
        while (experienceEntities.MoveNext(out var uid, out var _))
        {
            ExperienceEntityOption.AddItem(metadataQuery.TryComp(uid, out var metaDataComponent) ? $"{metaDataComponent.EntityName} ({metaDataComponent.NetEntity.Id})" : uid.ToString(), uid.Id);
        }

        ExperienceEntityOption.OnItemSelected += (args) =>
        {
            SelectEntity(args.Id);
        };

        foreach (var (key, proto) in _experienceEditor.CachedIndexedKnowledge)
        {
            KnowledgeOption.AddItem(FormattedMessage.RemoveMarkupPermissive(Loc.GetString(proto.KnowledgeName)), key);
        }

        SubmitButton.OnPressed += (_) =>
        {
            _experienceEditor.SendChange(new EntityUid(ExperienceEntityOption.SelectedId), GetChangedData());
        };

        KnowledgeOption.OnItemSelected += OnKnowledgeOptionSelected;

        SelectEntity(ExperienceEntityOption.SelectedId);
    }

    public void SelectEntity(int uid)
    {
        SelectEntity(new EntityUid(uid));
    }

    public void SelectEntity(EntityUid uid)
    {
        if (!_entityManager.TryGetComponent<ExperienceComponent>(uid, out var experience))
            return;

        if (!ExperienceEntityOption.TrySelectId(uid.Id))
            return;

        Entity<ExperienceComponent> experienceEntity = (uid, experience);

        var data = _experienceInfo.GetEntityExperienceData(uid);

        PopulateCharacterInfo(uid);
        PopulateExperienceVerification(experienceEntity);

        UpdateKnowledge(data);
        UpdateSkill(data);
    }

    public ExperienceData GetChangedData()
    {
        var data = new ExperienceData();

        foreach (var control in KnowledgeEditor.Children)
        {
            if (control is not KnowledgeLabel knowledgeLabel)
                continue;

            data.Knowledges.Add(knowledgeLabel.KnowledgeProto);
        }

        foreach (var control in SkillEditor.Children)
        {
            if (control is not RedactableSkillTreeShower redactableSkill)
                continue;

            var (skillId, skillInfo) = redactableSkill.GetInfo();

            if (!_prototype.Resolve(skillId, out var skillTreePrototype))
                continue;

            if (!data.SkillDictionary.TryGetValue(skillTreePrototype.SkillGroupId, out var definitionList))
            {
                definitionList = new();
                data.SkillDictionary.Add(skillTreePrototype.SkillGroupId, definitionList);
            }

            definitionList.Add(new(skillId, skillInfo, null, 0));
        }

        return data;
    }

    private void PopulateCharacterInfo(EntityUid uid)
    {
        CharacterName.SetMessage(_entityManager.TryGetComponent<MetaDataComponent>(uid, out var metaData) ? $"{metaData.EntityName} ({metaData.NetEntity.Id})" : uid.Id.ToString());

        if (!_entityManager.System<SharedMindSystem>().TryGetMind(uid, out var mindId, out var mindComponent))
            return;

        var roles = _entityManager.System<SharedRoleSystem>().MindGetAllRoleInfo(mindId);

        var job = roles.Any(x => !x.Antagonist);
        var antag = roles.Any(x => x.Antagonist);

        var jobName = job ? roles.First(x => !x.Antagonist).Name : Loc.GetString(NoJobName);
        var antagName = antag ? roles.First(x => x.Antagonist).Name : Loc.GetString(NoAntagRoleName);

        OccupationName.SetMessage(jobName);
        AntagName.SetMessage(antagName);
    }

    private void PopulateExperienceVerification(Entity<ExperienceComponent> entity)
    {
        BypassSkillCheckStatus.SetMessage(_entityManager.HasComponent<BypassSkillCheckComponent>(entity)
                                            ? Loc.GetString("experience-view-editor-bypass-skill")
                                            : Loc.GetString("experience-view-editor-no-bypass-skill"));

        BypassKnowledgeStatus.SetMessage(_entityManager.HasComponent<BypassKnowledgeCheckComponent>(entity)
                                            ? Loc.GetString("experience-view-editor-bypass-knowledge")
                                            : Loc.GetString("experience-view-editor-no-bypass-knowledge"));
    }

    private void UpdateKnowledge(ExperienceData data)
    {
        KnowledgeEditor.RemoveAllChildren();

        HighDivider? divider = null;
        foreach (var knowledge in data.Knowledges.OrderBy((x) => x.Id))
        {
            divider = new()
            {
                ModulateSelfOverride = ExperienceUiStyleDefinitions.InnerDividerColor,
            };
            var knowledgeControl = new KnowledgeLabel();
            knowledgeControl.SetKnowledge(knowledge);

            knowledgeControl.CloseButton.Visible = true;
            knowledgeControl.CloseButton.OnPressed += (_) =>
            {
                KnowledgeEditor.RemoveChild(knowledgeControl);
            };

            KnowledgeEditor.AddChild(knowledgeControl);
            KnowledgeEditor.AddChild(divider);
        }

        if (divider is not null)
            KnowledgeEditor.RemoveChild(divider);
    }

    private void UpdateSkill(ExperienceData data)
    {
        SkillEditor.RemoveAllChildren();

        HighDivider? divider = null;
        foreach (var (_, skillTreeViews) in data.SkillDictionary.OrderBy(x => x.Key))
        {
            foreach (var skillTreeView in skillTreeViews.OrderBy(x => x.SkillTreeId))
            {
                var redactableSkillTreeShower = new RedactableSkillTreeShower();
                redactableSkillTreeShower.SetSkillTreeInfo(skillTreeView.SkillTreeId, skillTreeView.Info);

                SkillEditor.AddChild(redactableSkillTreeShower);
            }

            divider = new()
            {
                Margin = ExperienceUiStyleDefinitions.DividerThickness,
                ModulateSelfOverride = ExperienceUiStyleDefinitions.InnerDividerColor,
            };
            SkillEditor.AddChild(divider);
        }

        if (divider is not null)
            SkillEditor.RemoveChild(divider);
    }

    private void OnKnowledgeOptionSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (!_experienceEditor.CachedIndexedKnowledge.TryGetValue(args.Id, out var knowledge))
            return;

        var divider = new HighDivider();
        var knowledgeControl = new KnowledgeLabel();
        knowledgeControl.SetKnowledge(knowledge.ID);

        knowledgeControl.CloseButton.Visible = true;
        knowledgeControl.CloseButton.OnPressed += (_) =>
        {
            KnowledgeEditor.RemoveChild(knowledgeControl);
        };

        KnowledgeEditor.AddChild(divider);
        KnowledgeEditor.AddChild(knowledgeControl);
    }
}
