using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls; // ss220 add toggle iff
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class RadarConsoleWindow : FancyWindow,
    IComputerWindow<NavInterfaceState>
{
    public RadarConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        // ss220 add toggle iff start
        IFFToggle.OnToggled += OnIFFTogglePressed;
        IFFToggle.Pressed = RadarScreen.ShowIFF;
        // ss220 add toggle iff end
    }

    public void UpdateState(NavInterfaceState scc)
    {
        RadarScreen.UpdateState(scc);
    }

    // ss220 add toggle iff start
    private void OnIFFTogglePressed(BaseButton.ButtonEventArgs args)
    {
        RadarScreen.ShowIFF ^= true;
        args.Button.Pressed = RadarScreen.ShowIFF;
    }
    // ss220 add toggle iff end
}
