// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Client.Administration.UI.BanList;
using Content.Shared.SS220.Administration.BanList;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.SS220.Administration.UI.BanList.SpeciesBans;

[GenerateTypedNameReferences]
public sealed partial class SpeciesBanListLine : BoxContainer, IBanListLine<SharedServerSpeciesBan>
{
    public SharedServerSpeciesBan Ban { get; }

    public event Action<SpeciesBanListLine>? IdsClicked;

    public SpeciesBanListLine(SharedServerSpeciesBan ban)
    {
        RobustXamlLoader.Load(this);

        Ban = ban;
        IdsHidden.OnPressed += IdsPressed;

        BanListEui.SetData(this, ban);
        Species.Text = ban.SpeciesId;
    }

    private void IdsPressed(ButtonEventArgs buttonEventArgs)
    {
        IdsClicked?.Invoke(this);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        IdsHidden.OnPressed -= IdsPressed;
        IdsClicked = null;
    }
}
