// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Client.Administration.UI.CustomControls;
using Content.Shared.SS220.Administration.BanList;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Administration.UI.BanList.SpeciesBans;

[GenerateTypedNameReferences]
public sealed partial class SpeciesBanListControl : Control
{
    public event Action<SpeciesBanListLine>? LineIdsClicked;

    public SpeciesBanListControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetSpeciesBans(List<SharedServerSpeciesBan> bans)
    {
        for (var i = SpeciesBans.ChildCount - 1; i >= 1; i--)
        {
            SpeciesBans.GetChild(i).Dispose();
        }

        foreach (var ban in bans)
        {
            SpeciesBans.AddChild(new HSeparator());

            var line = new SpeciesBanListLine(ban);
            line.IdsClicked += LineIdsClicked;

            SpeciesBans.AddChild(line);
        }
    }
}
