// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Administration.UI.BanList.SpeciesBans;

[GenerateTypedNameReferences]
public sealed partial class SpeciesBanListHeader : ContainerButton
{
    public SpeciesBanListHeader()
    {
        RobustXamlLoader.Load(this);
    }
}
