using System.Linq;
using System.Numerics;
using Content.Client.Resources;
using Content.Client.SS220.UserInterface.Controls;
using Content.Client.SS220.UserInterface.System.PinUI;
using Content.Client.Viewport;
using Content.Shared.DeviceNetwork;
using Content.Shared.SurveillanceCamera;
using Content.Shared.SurveillanceCamera.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.SurveillanceCamera.UI;

[GenerateTypedNameReferences]
public sealed partial class SurveillanceCameraMonitorWindow : DefaultWindow, IPinnableWindow // ss220 add pin for ui
{
    private static readonly ProtoId<ShaderPrototype> CameraStaticShader = "CameraStatic";

    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    // SS220 Camera-Map begin
    private enum TabNumbers
    {
        CameraMap,
        CameraList
    }

    public void SetMap(ResPath mapPath)
    {
        MapViewer.ViewedPicture = mapPath;
    }

    private string _subnetFilter = "";
    private Dictionary<string, Dictionary<string, (string, Vector2)>> _camerasCache = new();
    // SS220 Camera-Map end

    /// <summary>
    /// Triggered when a camera is selected.
    /// First parameter contains the camera's address.
    /// Second optional parameter contains a subnet - if possible, the monitor will switch to this subnet.
    /// </summary>
    public event Action<string, string?>? CameraSelected;

    public event Action<string>? CameraSelected;
    public event Action<string>? SubnetOpened;
    public event Action? CameraRefresh;
    public event Action? SubnetRefresh;
    public event Action? CameraSwitchTimer;
    public event Action? CameraDisconnect;

    private string _currentAddress = string.Empty;
    private string _currentName = string.Empty; // SS220 Camera-Map
    private bool _isSwitching;
    private readonly FixedEye _defaultEye = new();
    private readonly Dictionary<string, int> _subnetMap = new();
    private EntityUid? _mapUid;

    /*
    private string? SelectedSubnet
    {
        get
        {
            if (SubnetSelector.ItemCount == 0
                || SubnetSelector.SelectedMetadata == null)
            {
                return null;
            }

            return (string) SubnetSelector.SelectedMetadata;
        }
    }
    */

    public SurveillanceCameraMonitorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // This could be done better. I don't want to deal with stylesheets at the moment.
        var texture = _resourceCache.GetTexture("/Textures/Interface/Nano/square_black.png");
        var shader = _prototypeManager.Index(CameraStaticShader).Instance().Duplicate();

        CameraView.ViewportSize = new Vector2i(500, 500);
        CameraView.Eye = _defaultEye; // sure
        CameraViewBackground.Stretch = TextureRect.StretchMode.Scale;
        CameraViewBackground.Texture = texture;
        CameraViewBackground.ShaderOverride = shader;

        SubnetList.OnItemSelected += OnSubnetListSelect;

        SubnetSelector.OnItemSelected += args =>
        {
            // piss
            SubnetOpened?.Invoke((string) args.Button.GetItemMetadata(args.Id)!);
        };
        SubnetRefreshButton.OnPressed += _ => SubnetRefresh?.Invoke();
        SubnetRefreshButtonMap.OnPressed += _ => SubnetRefresh?.Invoke();
        CameraRefreshButton.OnPressed += _ => CameraRefresh?.Invoke();
        CameraDisconnectButton.OnPressed += _ => CameraDisconnect?.Invoke();

        CameraMap.EnableCameraSelection = true;
        CameraMap.CameraSelected += OnCameraMapSelected;
    }

    // The UI class should get the eye from the entity, and then
    // pass it here so that the UI can change its view.
    public void UpdateState(IEye? eye, HashSet<string> subnets, string activeAddress, Dictionary<string, Dictionary<string, (string, Vector2)>> cameras)
    {
        CameraMap.SetActiveCameraAddress(activeAddress);
        CameraMap.SetAvailableSubnets(subnets);

        _currentAddress = activeAddress;
        _currentName = string.Empty; //SS220 Camera-Map

        if (subnets.Count == 0)
        {
            SubnetSelector.AddItem(Loc.GetString("surveillance-camera-monitor-ui-no-subnets"));
            SubnetSelector.Disabled = true;
        }

        if (SubnetSelector.Disabled && subnets.Count != 0)
        {
            SubnetSelector.Clear();
            SubnetSelector.Disabled = false;
        }

        // if the subnet count is unequal, that means
        // we have to rebuild the subnet selector
        if (SubnetSelector.ItemCount != subnets.Count)
        {
            SubnetSelector.Clear();
            _subnetMap.Clear();

            foreach (var subnet in subnets)
            {
                var id = AddSubnet(subnet);
                _subnetMap.Add(subnet, id);
            }
        }

        PopulateCameraList(cameras);
        MapViewer.Populate(cameras);
        SetCameraView(eye);
    }

    private void PopulateCameraList(Dictionary<string, Dictionary<string, (string, Vector2)>> cameras)
    {
        // SS220 Camera-Map begin
        _camerasCache = cameras;

        var entries = new List<ItemList.Item>();
        foreach (var (subnetFreqId, subnetCameras) in cameras)
        {
            foreach (var (address, (name, _)) in subnetCameras)
            {
                if (address == _currentAddress)
                    _currentName = name;

                if (subnetFreqId == _subnetFilter)
                {
                    var item = new ItemList.Item(SubnetList)
                    {
                        Text = $"{name}: {address}",
                        Metadata = address
                    };
                    entries.Add(item);
                }
            }
        }

        //var entries = cameras.Select(i => new ItemList.Item(SubnetList) {
        //    Text = $"{i.Value}: {i.Key}",
        //    Metadata = i.Key
        //}).ToList();
        // SS220 Camera-Map end
        entries.Sort((a, b) => string.Compare(a.Text, b.Text, StringComparison.Ordinal));
        SubnetList.SetItems(entries, (a,b) => string.Compare(a.Text, b.Text));
    }

    private void SetCameraView(IEye? eye)
    {
        var eyeChanged = eye != CameraView.Eye || CameraView.Eye == null;
        CameraView.Eye = eye ?? _defaultEye;
        CameraView.Visible = !eyeChanged && !_isSwitching;
        CameraDisconnectButton.Disabled = eye == null;

        if (eye != null)
        {
            if (!eyeChanged)
            {
                return;
            }

            _isSwitching = true;
            CameraViewBackground.Visible = true;
            CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status",
                ("status", Loc.GetString("surveillance-camera-monitor-ui-status-connecting")),
                ("address", _currentAddress)) + $" ({_currentName})"; // SS220 Camera-Map
            CameraSwitchTimer!();
        }
        else
        {
            CameraViewBackground.Visible = true;
            CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status-disconnected");
        }
    }

    public void OnSwitchTimerComplete()
    {
        _isSwitching = false;
        CameraView.Visible = CameraView.Eye != _defaultEye;
        CameraViewBackground.Visible = CameraView.Eye == _defaultEye;
        CameraStatus.Text = Loc.GetString("surveillance-camera-monitor-ui-status",
                            ("status", Loc.GetString("surveillance-camera-monitor-ui-status-connected")),
                            ("address", _currentAddress)) + $" ({_currentName})"; // SS220 Camera-Map
    }

    private int AddSubnet(string subnet)
    {
        var name = subnet;
        if (_prototypeManager.TryIndex<DeviceFrequencyPrototype>(subnet, out var frequency))
        {
            name = Loc.GetString(frequency.Name ?? subnet);
        }

        SubnetSelector.AddItem(name);
        SubnetSelector.SetItemMetadata(SubnetSelector.ItemCount - 1, subnet);

        if (_subnetFilter == "")
            _subnetFilter = subnet;

        return SubnetSelector.ItemCount - 1;
    }

    private void OnSubnetListSelect(ItemList.ItemListSelectedEventArgs args)
    {
        CameraSelected!((string) SubnetList[args.ItemIndex].Metadata!, null);
    }

    public void SetMap(EntityUid mapUid)
    {
        CameraMap.MapUid = _mapUid = mapUid;
    }

    private void OnCameraMapSelected(NetEntity netEntity)
    {
        if (_mapUid is null || !_entityManager.TryGetComponent<SurveillanceCameraMapComponent>(_mapUid.Value, out var mapComp))
            return;

        if (!mapComp.Cameras.TryGetValue(netEntity, out var marker) || !marker.Active)
            return;

        if (!string.IsNullOrEmpty(marker.Address))
            CameraSelected?.Invoke(marker.Address, marker.Subnet);
        else
            _entityManager.RaisePredictiveEvent(new RequestCameraMarkerUpdateMessage(netEntity));
    }
}
