using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Headset;

[GenerateTypedNameReferences]
public sealed partial class HeadsetEncryptionRadioSetting : BoxContainer
{
    public Action<BaseButton.ButtonEventArgs, FixedPoint2>? OnFrequencySubmit;

    private int _minFrequency = 0;
    private int _maxFrequency = 0;

    public HeadsetEncryptionRadioSetting()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        SubmitButton.OnPressed += args =>
        {
            FrequencySetterSpinBox.Value = Math.Clamp(FrequencySetterSpinBox.Value, _minFrequency, _maxFrequency);
            OnFrequencySubmit?.Invoke(args, FixedPoint2.FromCents(FrequencySetterSpinBox.Value));
            ChangeApplyState(ApplyButtonStateEnum.ChangesSaved);
        };
    }

    public void Init(int minValue, int maxValue, int value)
    {
        FrequencySetterSpinBox.ClearButtons();

        FrequencySetterSpinBox.AddLeftButton(-50, "-50");
        FrequencySetterSpinBox.AddLeftButton(-10, "-10");
        FrequencySetterSpinBox.AddLeftButton(-1, "-1");
        FrequencySetterSpinBox.AddRightButton(1, "1");
        FrequencySetterSpinBox.AddRightButton(10, "10");
        FrequencySetterSpinBox.AddRightButton(50, "50");

        _minFrequency = minValue;
        _maxFrequency = maxValue;



        // it should be here to Force SpinBox UpdateButtonCanPress() cause its private
        FrequencySetterSpinBox.Value = Math.Clamp(value, _minFrequency, _maxFrequency);
        FrequencySetterSpinBox.ValueChanged += (_) =>
        {
            ChangeApplyState(ApplyButtonStateEnum.ChangesNotSaved);
        };
    }
    private void ChangeApplyState(ApplyButtonStateEnum state)
    {
        switch (state)
        {
            case ApplyButtonStateEnum.ChangesSaved:
                ChangeButtonLabelColor(SubmitButton, Color.LightGreen);
                SubmitDescription.Text = Loc.GetString("headset-ui-changes-saved");
                SubmitDescription.FontColorOverride = Color.LightGreen;
                break;
            case ApplyButtonStateEnum.ChangesNotSaved:
                ChangeButtonLabelColor(SubmitButton, Color.Orange);
                SubmitDescription.Text = Loc.GetString("headset-ui-changes-unsaved");
                SubmitDescription.FontColorOverride = Color.Orange;
                break;
        }
    }

    private void ChangeButtonLabelColor(Button button, Color color)
    {
        button.Label.FontColorOverride = color;
    }

    private enum ApplyButtonStateEnum
    {
        ChangesNotSaved = 0,
        ChangesSaved = 1
    }
}
