using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.ShuttleGunControl;

[GenerateTypedNameReferences]
public sealed partial class ShuttleGunControlRotateToPoint : BoxContainer
{
    public ShuttleGunControlRotateToPoint()
    {
        RobustXamlLoader.Load(this);
    }
}

