using Robust.Client.AutoGenerated;
using Content.Client.SS220.UserInterface.Controls;
using Content.Client.SS220.UserInterface.System.PinUI;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Logs;

[GenerateTypedNameReferences]
public sealed partial class AdminLogsWindow : DefaultWindow, IPinnableWindow // ss220 add pin for ui
{
    public AdminLogsWindow()
    {
        RobustXamlLoader.Load(this);

        // SS220 add pin button begin
        PinUISystem.AddPinButtonBeforeTarget(this, CloseButton);
        // SS220 add pin button end
    }
}
