- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10h # SS220-RoleTime
    #SS220-jobbans begin
    - !type:SpeciesRequirement
      inverted: true
      species:
      - Felinid
    #SS220-jobbans end
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityOfficerGear
  equipment:
#    eyes: ClothingEyesGlassesSecurity #SS220-Two Floppa Iteration
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Flash
    - MagazinePistol
    - MagazinePistol
    - FlashlightSeclite
    - DrinkRelaxingPeachCan #SS220-DeleteSecurityLetal-End

- type: chameleonOutfit
  id: SecurityOfficerChameleonOutfit
  job: SecurityOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretSecurity
    mask: ClothingMaskGasSecurity
    # neck: Dinkystar # SS220-more-robust-sec
    neck: ClothingBeltHolster # SS220-more-robust-sec
    gloves: ClothingHandsGlovesColorBlack
