// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Signature;

[GenerateTypedNameReferences]
public sealed partial class SignatureWindow : FancyWindow
{
    private static readonly Vector2 DefaultCanvasSize = new(250, 100);

    public SignatureWindow()
    {
        RobustXamlLoader.Load(this);
        Signature.CanvasSize = DefaultCanvasSize;
        Signature.SetSize = DefaultCanvasSize;
    }

    public SignatureWindow(Vector2 canvasSize)
    {
        RobustXamlLoader.Load(this);
        Signature.CanvasSize = canvasSize;
        Signature.SetSize = canvasSize;
    }
}

