- type: entity
  id: WardenGasLocker
  parent: LockerSleepingGasSecurity
  suffix: Filled
  name: шкаф с усыпляющим газом
  description: Стандартное хранилище Nanotrasen.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: NitrousOxideTankFilled
          amount: 3
        - id: ClothingMaskBreath
          amount: 3
        - id: ClothingOuterStraightjacket
          amount: 3

- type: entity
  id: LockerPilotFilled
  suffix: Filled
  parent: LockerPilot
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: FlashlightSeclite
        - id: WeaponDisabler
          prob: 0.3
        - id: ClothingOuterArmorBobmer
        - id: ClothingHeadHatPilotBeret
        - id: ClothingBeltSecurityFilled
        - id: Flash
        - id: ClothingEyesGlassesSecurity
        - id: BodySecurityCamera
        - id: ClothingShoesBootsJack
        - id: ClothingEyesHudSecurity
        - id: ClothingOuterHardsuitSecurityPilot
        - id: HandheldGPSBasic
        - id: OxygenTankFilled
        - id: NitrogenTankFilled
