- type: entity
  id: CrateDecKit
  parent: CrateSecgear
  name: detective kit
  description: A set of standard detective gear, in case the past has been lost. Contains box of forensic pads, box of evidence markers, box of tape recorder and cassettes for it
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: BoxForensicPad
        - id: BoxEvidenceMarkers
        - id: BoxTapeRecorder
