using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Pipes.DisposalFilter;

[GenerateTypedNameReferences]
public sealed partial class DisposalFilterByNameWindow : FancyWindow
{
    public DisposalFilterByNameWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

