- type: entity
  id: BaseStation
  abstract: true
  components:
    - type: StationData
    - type: StationMinimap #SS220 Camera-Map
      minimapData: !type:StationMinimapData
        mapScale: 5

- type: entity
  id: BaseStationCargo
  abstract: true
  components:
    - type: StationBankAccount
    - type: StationCargoOrderDatabase
      orders:
        Cargo: [ ]
        Engineering: [ ]
        Medical: [ ]
        Science: [ ]
        Security: [ ]
        Service: [ ]
    - type: StationCargoBountyDatabase

- type: entity
  id: BaseStationJobsSpawning
  abstract: true
  components:
    - type: StationJobs
      availableJobs: {}
    - type: StationSpawning

- type: entity
  id: BaseStationRecords
  abstract: true
  components:
    - type: StationRecords

- type: entity
  id: BaseStationArrivals
  abstract: true
  components:
    - type: StationArrivals

- type: entity
  id: BaseStationGateway
  abstract: true
  components:
    - type: GatewayGenerator

- type: entity
  id: BaseStationShuttles
  abstract: true
  components:
    - type: StationCargoShuttle
      path: /Maps/SS220/Shuttles/cargo.yml # SS220 shuttle upd
    - type: GridSpawn
      groups:
        trade: !type:GridSpawnGroup
          minimumDistance: 100 # SS220 make more space in space
          maximumDistance: 150 # SS220 make more space in space
          addComponents:
            - type: ProtectedGrid
            - type: TradeStation
          paths:
            - /Maps/SS220/Shuttles/trading_outpost.yml # SS220 shuttle upd
        mining: !type:GridSpawnGroup
          paths:
          - /Maps/SS220/Shuttles/mining.yml # SS220 shuttle upd
        # Spawn last
        ruins: !type:GridSpawnGroup
          hide: true #SS2200 IFF and Name Hide Reveal
          nameGrid: true #SS2200 IFF and Name Hide Reveal
          minCount: 8 # SS220-counter-ruin-rebalance
          maxCount: 12 # SS220-counter-ruin-rebalance
          stationGrid: false
          minimumDistance: 250 # SS220 Ruins distance
          maximumDistance: 350 # SS220 Ruins distance
          paths:
          - /Maps/Ruins/abandoned_outpost.yml
          - /Maps/Ruins/atmos_interchange.yml
          # - /Maps/Ruins/chunked_tcomms.yml # SS220 Removed with Ruins Update (balance Tweak)
          - /Maps/Ruins/biodome_satellite.yml
          - /Maps/Ruins/derelict.yml
          # - /Maps/Ruins/djstation.yml # SS220 Removed with Ruins Update (balance Tweak)
          # - /Maps/Ruins/empty_flagship.yml # SS220 Removed with Ruins Update (balance Tweak)
          - /Maps/Ruins/hydro_outpost.yml
          - /Maps/Ruins/old_ai_sat.yml
          - /Maps/Ruins/ruined_prison_ship.yml
          - /Maps/Ruins/syndicate_dropship.yml
          # - /Maps/Ruins/whiteship_ancient.yml # SS220 Removed with Ruins Update (balance Tweak)
          # - /Maps/Ruins/whiteship_bluespacejumper.yml # SS220 Removed with Ruins Update (balance Tweak)
          # - /Maps/Ruins/wrecklaimer.yml # SS220 Removed with Ruins Update (balance Tweak)
          - /Maps/Ruins/displaced_telescience.yml
      # SS220 Ruins Update Map begin
          - /Maps/SS220/Ruins/Arena_SS220.yml
          - /Maps/SS220/Ruins/Broadaxe_SS220.yml
          - /Maps/SS220/Ruins/CargoOutpost_SS220.yml
          - /Maps/SS220/Ruins/Prison_SS220.yml
          - /Maps/SS220/Ruins/WarshuttleWreck_SS220.yml
          - /Maps/SS220/Ruins/Warehouse_SS220.yml
          - /Maps/SS220/Ruins/Market_SS220.yml
          - /Maps/SS220/Ruins/Scrapyard_SS220.yml
          - /Maps/SS220/Ruins/TradeCenter_SS220.yml
          - /Maps/SS220/Ruins/SyndiBase_SS220.yml
          - /Maps/SS220/Ruins/Chapel_SS220_RuinVer.yml
          - /Maps/SS220/Ruins/SmallJRBarge_SS220_RuinVer.yml
          - /Maps/SS220/Ruins/EngineeringChunk_SS220_RuinVer.yml
          - /Maps/SS220/Ruins/AsteroidBase_SS220_RuinVer.yml
          - /Maps/SS220/Ruins/SmallCargoWreck_SS220_RuinVer.yml
          addComponents:
          - type: Shuttle
            bodyModifier: 2
          - type: IFF
            flags: HideLabel
            color: "#d1af88"
        satellites: !type:GridSpawnGroup
          hide: false
          nameGrid: true
          minCount: 1
          maxCount: 1
          stationGrid: false
          minimumDistance: 150
          maximumDistance: 250
          paths:
          - /Maps/SS220/Ruins/CargoOutpost_SS220.yml
          - /Maps/SS220/Ruins/Prison_SS220.yml
          - /Maps/SS220/Ruins/BDDarkForest_SS220.yml
          - /Maps/SS220/Ruins/BDGrass_SS220.yml
          - /Maps/SS220/Ruins/GasStation_SS220.yml
          addComponents:
          - type: Shuttle
            bodyModifier: 2
        # SS220 Ruins Update Map End
        wrecks: !type:DungeonSpawnGroup
          hide: true #SS2200 IFF and Name Hide Reveal
          minimumDistance: 150
          maximumDistance: 250 # SS220-move-dungeon-closer
          stationGrid: false
          minCount: 12
          maxCount: 16
          addComponents:
          - type: Gravity
            enabled: true
            inherent: true
          - type: IFF
            flags: HideLabel
            color: "#88b0d1"
          protos:
          - ChunkDebrisSmall
          - ChunkDebrisSmall
          - ChunkDebrisSmall
          - ChunkDebrisSmall
          - ChunkDebris
        vgroid: !type:DungeonSpawnGroup
          hide: true #SS2200 IFF and Name Hide Reveal
          minimumDistance: 900 # SS220 VGroid distance
          maximumDistance: 1350 # SS220 VGroid distance
          nameDataset: NamesBorer
          stationGrid: false
          addComponents:
          - type: Gravity
            enabled: true
            inherent: true
          protos:
          - VGRoid

- type: entity
  id: BaseStationCentcomm
  abstract: true
  components:
    - type: StationCentcomm

- type: entity
  id: BaseStationEvacuation
  abstract: true
  components:
    - type: StationEmergencyShuttle

- type: entity
  id: BaseStationAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: stationAlerts

- type: entity
  id: BaseStationExpeditions
  abstract: true
  components:
    - type: SalvageExpeditionData

- type: entity
  id: BaseStationMagnet
  abstract: true
  components:
    - type: SalvageMagnetData

- type: entity
  id: BaseStationSalvageJobs
  abstract: true
  components:
  - type: SalvageJobsData
    rankThresholds:
      0:
        title: salvage-job-rank-title-0
        bountyGroup: SalvageJobTier1
      3:
        title: salvage-job-rank-title-1
        bountyGroup: SalvageJobTier2
        unlockedMarket: SalvageJobReward2
      6:
        title: salvage-job-rank-title-2
        bountyGroup: SalvageJobTier3
        unlockedMarket: SalvageJobReward3
    maxRank:
      title: salvage-job-rank-title-MAX
      unlockedMarket: SalvageJobRewardMAX

- type: entity
  id: BaseStationSiliconLawCrewsimov
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Crewsimov

- type: entity
  id: BaseStationNews
  abstract: true
  components:
    - type: StationNews

- type: entity
  id: BaseStationDeliveries
  abstract: true
  components:
  - type: CargoDeliveryData

- type: entity
  id: BaseStationAllEventsEligible
  abstract: true
  components:
    - type: StationEventEligible # For when someone makes this more granular in the future.
