// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;

namespace Content.Client.SS220.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class AddObjectiveWindow : DefaultWindow
{
    private ICommonSession? _selectedAntagonist;
    private string _input = string.Empty;
    private string _entityId = string.Empty;

    public AddObjectiveWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void EnteredTree()
    {
        ApplyButton.OnPressed += _ => OnApplyButtonPressed(false);
        ForceAssignButton.OnPressed += _ => OnApplyButtonPressed(true);
        ObjectiveLineEdit.OnTextChanged += args => _input = args.Text;
        EntityIdLineEdit.OnTextChanged += args => _entityId = args.Text;
    }

    public void SetAntagonist(ICommonSession antagonistPlayerName)
    {
        _selectedAntagonist = antagonistPlayerName;
    }

    private void OnApplyButtonPressed(bool force)
    {
        if (_input.Length == 0)
            return;

        IoCManager.Resolve<IClientConsoleHost>().ExecuteCommand($"addobjective {_selectedAntagonist} {_input} {_entityId} {force}");
    }
}
