// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Shared.Objectives.Systems;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;

namespace Content.Client.SS220.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class AddObjectiveWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    private ICommonSession? _selectedAntagonist;
    private bool _customObjective;

    public AddObjectiveWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var objective = _entMan.System<SharedObjectivesSystem>();

        if (objective.ObjectivesQuery == null)
            return;

        ObjectiveOptionButton.AddItem(Loc.GetString("ui-add-objective-option-button-placeholder"), 0);

        var index = 1;

        foreach (var objId in objective.ObjectivesQuery)
        {
            ObjectiveOptionButton.AddItem(objId, index);
            ObjectiveOptionButton.SetItemMetadata(index, objId);
            index++;
        }
    }

    protected override void EnteredTree()
    {
        ApplyButton.OnPressed += _ => OnApplyButtonPressed(false);
        ForceAssignButton.OnPressed += _ => OnApplyButtonPressed(true);

        ObjectiveOptionButton.OnItemSelected += args =>
        {
            ObjectiveOptionButton.SelectId(args.Id);
            UpdateInputStates();
        };

        EntityIdLineEdit.OnTextChanged += _ => UpdateInputStates();
        CustomObjectiveNameLineEdit.OnTextChanged += _ => UpdateInputStates();
        CustomObjectiveDescLineEdit.OnTextChanged += _ => UpdateInputStates();
        CustomObjectiveIconLineEdit.OnTextChanged += _ => UpdateInputStates();
        CustomObjectiveIssuerLineEdit.OnTextChanged += _ => UpdateInputStates();
    }

    private void UpdateInputStates()
    {
        var hasUsualText = ObjectiveOptionButton.SelectedMetadata != null ||
                           !string.IsNullOrWhiteSpace(EntityIdLineEdit.Text);

        var hasCustomText = !string.IsNullOrWhiteSpace(CustomObjectiveNameLineEdit.Text) ||
                            !string.IsNullOrWhiteSpace(CustomObjectiveDescLineEdit.Text) ||
                            !string.IsNullOrWhiteSpace(CustomObjectiveIconLineEdit.Text) ||
                            !string.IsNullOrWhiteSpace(CustomObjectiveIssuerLineEdit.Text);

        UsualObjectiveContainer.Visible = !hasCustomText;
        CustomObjectiveContainer.Visible = !hasUsualText;

        _customObjective = hasCustomText;
    }

    public void SetAntagonist(ICommonSession antagonistPlayerName)
    {
        _selectedAntagonist = antagonistPlayerName;
    }

    private void OnApplyButtonPressed(bool force)
    {
        if (_selectedAntagonist == null)
            return;

        var clientHost = IoCManager.Resolve<IClientConsoleHost>();

        if (_customObjective)
        {
            var name = CustomObjectiveNameLineEdit.Text;
            if (string.IsNullOrWhiteSpace(name))
                return;

            var desc = CustomObjectiveDescLineEdit.Text;
            var icon = CustomObjectiveIconLineEdit.Text;
            var issuer = CustomObjectiveIssuerLineEdit.Text;

            clientHost.ExecuteCommand($"addcustomobjective {_selectedAntagonist.Name} \"{name}\" \"{desc}\" \"{icon}\" \"{issuer}\"");
        }
        else
        {
            var objectiveId = ObjectiveOptionButton.SelectedMetadata as string;
            var entityId = EntityIdLineEdit.Text;
            if (string.IsNullOrEmpty(objectiveId) && string.IsNullOrWhiteSpace(entityId))
                return;

            clientHost.ExecuteCommand($"addobjective {_selectedAntagonist.Name} \"{objectiveId}\" \"{entityId}\" {force}");
        }
    }
}
