// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Numerics;
using Robust.Client.Player;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.SS220.GhostRoleCast;
using Robust.Shared.Timing;

namespace Content.Client.SS220.GhostRoleCast;

[GenerateTypedNameReferences]
public sealed partial class GhostRoleCastWindow : DefaultWindow
{
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly EntityManager _entityManager = default!;

    public GhostRoleCastWindow()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var uid = _playerManager.LocalEntity;
        if (uid == null)
            return;

        if (!_entityManager.TryGetComponent<GhostRoleCastComponent>(uid, out var component))
            return;

        component.GhostRoleName = RoleName.Text;
        component.GhostRoleDesc = RoleDescription.Text;
        component.GhostRoleRule = RoleRules.Text;
    }
}
