using Robust.Client.AutoGenerated;
using Content.Client.SS220.UserInterface.Controls;
using Content.Client.SS220.UserInterface.System.PinUI;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Bwoink
{
    /// <summary>
    /// This window connects to a BwoinkSystem channel. BwoinkSystem manages the rest.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class BwoinkWindow : DefaultWindow, IPinnableWindow // ss220 add pin for ui
    {
        public BwoinkWindow()
        {
            RobustXamlLoader.Load(this);

            Bwoink.ChannelSelector.OnSelectionChanged += sel =>
            {
                if (sel is null)
                {
                    Title = Loc.GetString("bwoink-title-none-selected");
                    return;
                }

                Title = $"{sel.CharacterName} / {sel.Username} | {Loc.GetString("generic-playtime-title")}: ";

                Title += sel.OverallPlaytime != null ? sel.PlaytimeString : Loc.GetString("generic-unknown-title");
            };

            OnOpen += () =>
            {
                Bwoink.ChannelSelector.StopFiltering();
                Bwoink.PopulateList();
            };

            // SS220 add pin button begin
            PinUISystem.AddPinButtonBeforeTarget(this, CloseButton);
            // SS220 add pin button end
        }
    }
}
