// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Content.Client.Guidebook.Richtext;
using Content.Client.SS220.Experience.UiElements;
using Content.Shared.SS220.Experience;
using Content.Shared.SS220.Experience.Systems;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Guidebook.Controls;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class AllKnowledgeShower : BoxContainer, IDocumentTag
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public AllKnowledgeShower()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        foreach (var knowledge in _prototype.EnumeratePrototypes<KnowledgePrototype>().OrderBy(x => Loc.GetString(x.KnowledgeName)))
        {
            var knowledgeLabel = new KnowledgeLabel();

            KnowledgesContainer.AddChild(knowledgeLabel);

            knowledgeLabel.SetKnowledge(knowledge);
        }
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        control = this;
        return true;
    }
}
