// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Shared.SS220.Experience;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Guidebook.Controls;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class SkillPrototypeShower : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public SkillPrototypeShower()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateSkillInfo(ProtoId<SkillPrototype> skillId, int level)
    {
        if (!_prototype.Resolve(skillId, out var skillPrototype))
            return;

        SkillLevelText.SetMarkup(Loc.GetString("skill-prototype-shower-level-text", ("level", level)));
        SkillName.SetMarkup(Loc.GetString(skillPrototype.LevelDescription.SkillName));

        SkillDescription.SetMarkup(Loc.GetString(skillPrototype.LevelDescription.SkillDescription));
        SkillSublevelText.SetMarkup(Loc.GetString("skill-prototype-shower-sublevel-text", ("sublevels", skillPrototype.LevelInfo.MaximumSublevel)));
    }

}
