// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Diagnostics.CodeAnalysis;
using Content.Client.Guidebook.Richtext;
using Content.Client.Message;
using Content.Shared.SS220.Experience;
using Content.Shared.SS220.Experience.Systems;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Guidebook.Controls;

[UsedImplicitly, GenerateTypedNameReferences]
public sealed partial class SkillTreePrototypeShower : BoxContainer, IDocumentTag
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly ISawmill _sawmill;

    public ProtoId<SkillTreePrototype> SKillTreeId
    {
        set => UpdateSkillTreeInfo(value);
    }

    public SkillTreePrototypeShower()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = IoCManager.Resolve<ILogManager>().GetSawmill("guidebook.skillTreeShower");
    }

    public void UpdateSkillTreeInfo(ProtoId<SkillTreePrototype> skillTreeId)
    {
        if (!_prototype.Resolve(skillTreeId, out var skillTreeProto))
            return;

        TreeNameLabel.SetMarkup(Loc.GetString(skillTreeProto.SkillTreeName));

        SkillsContainer.RemoveAllChildren();

        var counter = 0;
        foreach (var skill in skillTreeProto.SkillTree)
        {
            var skillShower = new SkillPrototypeShower();

            SkillsContainer.AddChild(skillShower);

            skillShower.UpdateSkillInfo(skill, ExperienceSystem.StartSkillLevel + (counter++));
        }
    }

    public bool TryParseTag(Dictionary<string, string> args, [NotNullWhen(true)] out Control? control)
    {
        if (!args.TryGetValue("SKillTreeId", out var protoId))
        {
            _sawmill.Error("Entity embed tag is missing entity prototype argument");
            control = null;
            return false;
        }

        UpdateSkillTreeInfo(protoId);

        control = this;
        return true;
    }
}
