// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.MindExtension.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostAdditionGui : UIWidget
{
    public event Action? OnRespawnPressed;
    public event Action? OnReturnToBodyPressed;

    public GhostBodyMenuWindow BodyMenuWindow { get; }

    public GhostAdditionGui()
    {
        RobustXamlLoader.Load(this);

        BodyMenuWindow = new GhostBodyMenuWindow();

        RespawnButton.OnPressed += _ => OnRespawnPressed?.Invoke();
        BodyMenuButton.OnPressed += _ => OnReturnToBodyPressed?.Invoke();
    }

    public void SetRespawnRemainTimer(TimeSpan respawnRemainTime)
    {
        if (respawnRemainTime > TimeSpan.Zero)
        {
            RespawnButton.Text = Loc.GetString("mind-ext-respawn-button",
                ("Timer", "WithTimer"),
                ("RespawnTimeRemain", respawnRemainTime.ToString("mm\\:ss")));
            RespawnButton.Disabled = true;
        }
        else
        {
            RespawnButton.Text = Loc.GetString("mind-ext-respawn-button");
            RespawnButton.Disabled = false;
        }

    }

    public void LockRespawnTimer()
    {
        RespawnButton.Text = Loc.GetString("mind-ext-respawn-button");
        RespawnButton.Disabled = true;
    }
}

