// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Shared.SS220.MindExtension;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.MindExtension.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostBodyMenuWindow : DefaultWindow
{
    private Dictionary<NetEntity, GhostBodyCard> _bodyCards = new Dictionary<NetEntity, GhostBodyCard>();

    public Action<NetEntity>? OnFollowBodyAction;
    public Action<NetEntity>? OnToBodyAction;
    public Action<NetEntity>? OnDeleteTrailPointAction;

    public GhostBodyMenuWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateBodies(IEnumerable<TrailPoint> bodies)
    {
        _bodyCards.Clear();
        BodyList.DisposeAllChildren();

        foreach (var body in bodies)
        {
            var bodyCard = new GhostBodyCard();
            bodyCard.Init(body);

            bodyCard.OnFollowBodyAction += OnFollowBodyAction;
            bodyCard.OnToBodyAction += OnToBodyAction;
            bodyCard.OnDeleteTrailPointAction += OnDeleteTrailPointAction;

            BodyList.AddChild(bodyCard);
            _bodyCards.Add(body.Id, bodyCard);
        }
    }

    public void DeleteBodyCard(NetEntity entity)
    {
        if (!_bodyCards.TryGetValue(entity, out var bodyCard))
            return;

        bodyCard.OnFollowBodyAction -= OnFollowBodyAction;
        bodyCard.OnToBodyAction -= OnToBodyAction;
        bodyCard.OnDeleteTrailPointAction -= OnDeleteTrailPointAction;

        BodyList.RemoveChild(bodyCard);
        _bodyCards.Remove(entity);
    }
}
