// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Shared.SS220.MindExtension;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.MindExtension.UI;

[GenerateTypedNameReferences]
public sealed partial class GhostBodyCard : UIWidget
{
    public Action<NetEntity>? OnFollowBodyAction;
    public Action<NetEntity>? OnToBodyAction;
    public Action<NetEntity>? OnDeleteTrailPointAction;

    private TrailPoint _trailPoint;

    private readonly Color _availableColorConst = Color.Green;
    private readonly Color _adminAvailableColorConst = Color.Yellow;
    private readonly Color _unavailableColorConst = Color.Red;

    public GhostBodyCard()
    {
        RobustXamlLoader.Load(this);
    }
    public void Init(TrailPoint trailPoint)
    {
        _trailPoint = trailPoint;

        BodyNameLabel.Text = trailPoint.MetaData.EntityName;
        BodyDescriptionLabel.Text = trailPoint.MetaData.EntityDescription;

        switch (trailPoint.State)
        {
            case BodyStateToEnter.Available:
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-available");
                SetAvailableState();
                break;
            case BodyStateToEnter.Abandoned:
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-abandoned");

                if (trailPoint.ByAdmin)
                    SetAdminAvailableState();
                else
                    SetUnavailableState();

                break;
            case BodyStateToEnter.Engaged:
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-engaged");

                if (trailPoint.ByAdmin)
                    SetAdminAvailableState();
                else
                    SetUnavailableState();

                break;
            case BodyStateToEnter.InCryo:
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-incryo");
                SetInvalidState();
                break;
            case BodyStateToEnter.Destroyed:
                BodyStateLabel.Text = Loc.GetString("mind-ext-body-state-destroyed");
                SetInvalidState();
                break;
        }

        FollowButton.OnButtonDown += _ => OnFollowBodyAction?.Invoke(_trailPoint.Id);
        ToBodyButton.OnButtonDown += _ => OnToBodyAction?.Invoke(_trailPoint.Id);
        DeleteButton.OnPressed += _ => OnDeleteTrailPointAction?.Invoke(_trailPoint.Id);
    }

    private void SetAvailableState()
    {
        FollowButton.Disabled = false;
        ToBodyButton.Disabled = false;

        BodyStateLabel.FontColorOverride = _availableColorConst;
    }

    private void SetAdminAvailableState()
    {
        FollowButton.Disabled = false;
        ToBodyButton.Disabled = false;

        BodyStateLabel.FontColorOverride = _adminAvailableColorConst;
    }

    private void SetUnavailableState()
    {
        FollowButton.Disabled = false;
        ToBodyButton.Disabled = true;

        BodyStateLabel.FontColorOverride = _unavailableColorConst;
    }

    private void SetInvalidState()
    {
        FollowButton.Disabled = true;
        ToBodyButton.Disabled = true;

        BodyStateLabel.FontColorOverride = _unavailableColorConst;
    }
}
