// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt
using System.Numerics;
using Content.Client.Humanoid;
using Content.Client.Inventory;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Content.Shared.Clothing;
using Content.Shared.Humanoid;
using Robust.Client.GameObjects;
using Robust.Client.Player;

namespace Content.Client.SS220.CriminalRecords.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterVisualisation : BoxContainer
{
    private readonly IEntityManager _entMan;
    private readonly IPrototypeManager _prototype;
    private readonly IPlayerManager _player;
    private readonly ClientInventorySystem _inventorySystem;
    private readonly SpriteSystem _sprite;
    private EntityUid _previewDummy;

    private readonly SpriteView? _face;
    private readonly SpriteView? _side;

    [ViewVariables(VVAccess.ReadWrite)]
    public Vector2 FaceScale { get; set; } = new Vector2(5f, 5f);

    [ViewVariables(VVAccess.ReadWrite)]
    public Vector2 SideScale { get; set; } = new Vector2(5f, 5f);

    [ViewVariables(VVAccess.ReadWrite)]
    public bool IsOnlyFace { get; set; }

    [ViewVariables(VVAccess.ReadWrite)]
    public bool IsOnlySide { get; set; }

    public CharacterVisualisation()
    {
        RobustXamlLoader.Load(this);

        _entMan = IoCManager.Resolve<IEntityManager>();
        _prototype = IoCManager.Resolve<IPrototypeManager>();
        _player = IoCManager.Resolve<IPlayerManager>();
        _inventorySystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<ClientInventorySystem>();
        _sprite = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

        if (IsOnlyFace || !IsOnlySide)
        {
            _face = new SpriteView
            {
                Scale = FaceScale,
            };
            AddChild(_face);
        }

        if (IsOnlySide || !IsOnlyFace)
        {
            _side = new SpriteView
            {
                Scale = SideScale,
                OverrideDirection = Direction.East,
            };
            AddChild(_side);
        }
    }

    public void ResetCharacterSpriteView()
    {
        _face?.SetEntity(null);
        _side?.SetEntity(null);
        _entMan.DeleteEntity(_previewDummy);
    }

    private void SetEntity()
    {
        if (IsOnlyFace && !IsOnlySide)
        {
            _face?.SetEntity(_previewDummy);
        }
        else if (IsOnlySide && !IsOnlyFace)
        {
            _side?.SetEntity(_previewDummy);
        }
        else
        {
            _face?.SetEntity(_previewDummy);
            _side?.SetEntity(_previewDummy);
        }
    }

    public void SetupEntitySpriteView(EntityUid target, EntProtoId dollPrototype)
    {
        var appearanceSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<HumanoidAppearanceSystem>();

        _entMan.DeleteEntity(_previewDummy);
        _previewDummy = _entMan.SpawnEntity(dollPrototype, MapCoordinates.Nullspace);
        _entMan.EnsureComponent<HumanoidAppearanceComponent>(_previewDummy);
        _entMan.EnsureComponent<SpriteComponent>(_previewDummy);

        appearanceSystem.CloneAppearance(target, _previewDummy);
        _sprite.CopySprite(target, _previewDummy);

        SetEntity();
    }

    public void SetupCharacterSpriteView(HumanoidCharacterProfile profile, string jobPrototype)
    {
        var appearanceSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<HumanoidAppearanceSystem>();

        _entMan.DeleteEntity(_previewDummy);

        _previewDummy = _entMan.SpawnEntity(_prototype.Index(profile.Species).DollPrototype, MapCoordinates.Nullspace);
        appearanceSystem.LoadProfile(_previewDummy, profile);
        var realJobPrototype = _prototype.Index<JobPrototype>(jobPrototype);
        GiveDummyJobClothes(_previewDummy, profile, realJobPrototype);

        SetEntity();
    }

    private void GiveDummyJobClothes(EntityUid dummy, HumanoidCharacterProfile profile, JobPrototype job)
    {
        if (!_inventorySystem.TryGetSlots(dummy, out var slots))
            return;

        if (job.StartingGear == null)
            return;

        var gear = _prototype.Index<StartingGearPrototype>(job.StartingGear);

        foreach (var slot in slots)
        {
            var itemType = ((IEquipmentLoadout) gear).GetGear(slot.Name);

            if (_inventorySystem.TryUnequip(dummy, slot.Name, out var unequippedItem, silent: true, force: true, reparent: false))
                _entMan.DeleteEntity(unequippedItem.Value);

            if (itemType != string.Empty)
            {
                var item = _entMan.SpawnEntity(itemType, MapCoordinates.Nullspace);
                _inventorySystem.TryEquip(dummy, item, slot.Name, silent: true, force: true);
            }
        }

        if (profile.Loadouts.TryGetValue(LoadoutSystem.GetJobPrototype(job.ID), out var jobLoadout))
            GiveDummyLoadout(dummy, jobLoadout);
        else
        {
            jobLoadout = new RoleLoadout(LoadoutSystem.GetJobPrototype(job.ID));
            jobLoadout.SetDefault(profile, _player.LocalSession, _prototype);
            GiveDummyLoadout(dummy, jobLoadout);
        }
    }

    private void GiveDummyLoadout(EntityUid dummy, RoleLoadout jobLoadout)
    {
        if (!_inventorySystem.TryGetSlots(dummy, out var slots))
            return;

        foreach (var loadouts in jobLoadout.SelectedLoadouts.Values)
        {
            foreach (var loadout in loadouts)
            {
                if (!_prototype.TryIndex(loadout.Prototype, out var loadoutProto))
                    continue;

                foreach (var slot in slots)
                {
                    var itemType = ((IEquipmentLoadout) loadoutProto).GetGear(slot.Name);

                    if (string.IsNullOrEmpty(itemType))
                        continue;

                    var item = _entMan.SpawnEntity(itemType, MapCoordinates.Nullspace);
                    _inventorySystem.TryEquip(dummy, item, slot.Name, silent: true, force: true);
                }
            }
        }
    }
}
