name: "NDA Team Contributor Accepted"

on:
  issue_comment:
    types: [created]

jobs:
  accept-contributor:
    if: >
      github.event.issue.pull_request &&
      contains(github.event.comment.body, 'Я согласен') &&
      contains(github.event.issue.labels.*.name, 'nda-pending')
    runs-on: ubuntu-latest
    steps:
      - name: Check author and accept
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.PAT_INVITE_CONTRIBUTOR_TOKEN }}
          script: |
            if (context.payload.comment.user.logn !== context.payload.issue.user.login) {
              return;
            }
            try {
              await github.rest.teams.addOrUpdateMembershipForUserInOrg({
                org: 'SerbiaStrong-220',
                team_slug: 'read-only-contributor',
                username: context.payload.comment.user.login,
                role: 'member';
              });
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `✅ **${context.payload.comment.user.login}**, соглашение принято! Приглашение отправлено. \n\n👉 **[Принять приглашение можно по этой ссылке](https://github.com/orgs/SerbiaStrong-220/invitation)** (или проверьте почту). Добро пожаловать!`
              });
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'nda-pending'
              });
            } catch (error) {
              console.error(error);
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `❌ Ошибка при добавлении в команду. @review-managers приглашены для выяснения обстаятельств.`
              });
            }
