name: "Mapping issues"

on:
  issues:
    types: [opened]

jobs:
  add-labels-and-link:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.REVIEWER_APP }}
          private-key: ${{ secrets.REVIEWER_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Check & link
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const issueLabels = context.payload.issue.labels.map(l => l.name);
            const issueBody = context.payload.issue.body || '';

            if (!issueLabels.includes('Mapping Issues')) {
              console.log('Not mapping issue. Skip action.');
              return;
            }

            const options = {
              'Frankenstein': { parentIssue: 789 },
              'Axioma': { parentIssue: 790 },
              'Donuts': { parentIssue: 793 },
              'Eclipse': { parentIssue: 791 },
              'Astro': { parentIssue: 792 },
              'Nightshift': { parentIssue: 794 },
              'Tox': { parentIssue: 795 },
              'Другое': { parentIssue: 788 }
            };

            let selectedOption = null;
            for (const option in options){
              if (issueBody.includes(option)) {
                selectedOption = options[option];
                break;
              }
            }

            if (selectedOption && selectedOption.parentIssue) {
              const targetOwner = 'SerbiaStrong-220';
              const targetRepo = 'DevTeam220';

              const subIssueId = context.payload.issue.id;

              try {
                await github.request('POST /repos/{owner}/{repo}/issues/{issue_number}/sub_issues', {
                  owner: targetOwner,
                  repo: targetRepo,
                  issue_number: selectedOption.parentIssue,
                  sub_issue_id: subIssueId,
                  headers: {
                    'X-GitHub-Api-Version': '2026-03-10',
                    'accept': 'application/vnd.github+json'
                  }
                });
                console.log(`Linked #${context.issue.number} to ${targetOwner}/${targetRepo}#${selectedOption.parentIssue}`);
              } catch (error) {
                console.error(`Failed to link #${selectedOption.parentIssue}`, error);
                if (error.response) {
                  console.error('API:', error.response.data);
                }
              }
            } else {
              console.log('No options');
            }
