// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using Content.Shared.SS220.Experience;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.SS220.Experience.UiElements;

[GenerateTypedNameReferences]
public sealed partial class ExperienceSkillTreeGroupContainer : BoxContainer
{
    private Dictionary<ProtoId<SkillTreePrototype>, ExperienceTreeContainer> _cachedTreeContainers = new();

    private string _name = string.Empty;

    public new string Name => _name;

    public ExperienceSkillTreeGroupContainer()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateWithList(Span<SkillTreeView> skillTreeViews, ProtoId<SkillTreeGroupPrototype> groupProto)
    {
        foreach (ref var treeView in skillTreeViews)
        {
            if (!_cachedTreeContainers.TryGetValue(treeView.SkillTreeId, out var cachedControl))
            {
                cachedControl = new ExperienceTreeContainer();
                _cachedTreeContainers.Add(treeView.SkillTreeId, cachedControl);
            }

            cachedControl.SetInfo(ref treeView);
        }

        SkillTreeContainer.RemoveAllChildren();
        foreach (var treeContainer in _cachedTreeContainers.Select(x => x.Value).OrderBy(x => x.Name))
        {
            SkillTreeContainer.AddChild(treeContainer);
        }
    }

    public void SetGroupName(FormattedMessage message)
    {
        GroupName.SetMessage(message);
        _name = message.ToString();
    }
}
