// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using Content.Client.Message;
using Content.Client.SS220.Experience.Ui;
using Content.Shared.SS220.Experience;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Experience.UiElements;

[GenerateTypedNameReferences]
public sealed partial class KnowledgeLabel : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public ProtoId<KnowledgePrototype> KnowledgeProto { private set; get; }

    public KnowledgeLabel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetKnowledge(ProtoId<KnowledgePrototype> knowledge)
    {
        if (!_prototype.Resolve(knowledge, out var knowledgePrototype))
            return;

        KnowledgeProto = knowledge;

        KnowledgeName.SetMarkup(Loc.GetString(knowledgePrototype.KnowledgeName));

        KnowledgeName.TooltipSupplier = ExperienceUiStyleDefinitions.RichExperienceTooltip;
        KnowledgeName.ToolTip = Loc.GetString(knowledgePrototype.KnowledgeDescription);
    }

}
