// © SS220, An EULA/CLA with a hosting restriction, full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/CLA.txt

using System.Linq;
using Content.Shared.SS220.Experience;
using Content.Shared.SS220.Experience.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.SS220.Experience.UiElements;

[GenerateTypedNameReferences]
public sealed partial class RedactableSkillTreeShower : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private ProtoId<SkillTreePrototype> _skillTreeId;
    private SkillTreeInfo _skillTreeInfo = new();

    private int _maxLevel;
    private List<int> _maxSublevels = new();

    public RedactableSkillTreeShower()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SkillLevel.OnFocusExit += OnSkillLevelChange;
        SkillSublevel.OnFocusExit += OnSkillSublevelChange;
    }

    public void SetSkillTreeInfo(ProtoId<SkillTreePrototype> skillTreeId, in SkillTreeInfo info)
    {
        if (!_prototype.Resolve(skillTreeId, out var skillTree))
            return;

        _skillTreeId = skillTreeId;
        SkillTreeName.SetMessage(Loc.GetString(skillTree.SkillTreeName));

        _maxLevel = skillTree.SkillTree.Count;
        _maxSublevels = [.. skillTree.SkillTree.Select(x => _prototype.Index(x).LevelInfo.MaximumSublevel)];

        _skillTreeInfo = new(info);

        UpdateLineEdits();
    }

    public (ProtoId<SkillTreePrototype>, SkillTreeInfo) GetInfo()
    {
        return (_skillTreeId, _skillTreeInfo);
    }

    private void UpdateLineEdits()
    {
        SkillLevel.SetText($"{_skillTreeInfo.Level}/{_maxLevel}");
        SkillSublevel.SetText($"{_skillTreeInfo.Sublevel}/{_maxSublevels[_skillTreeInfo.SkillTreeIndex]}");
    }

    private void OnSkillLevelChange(LineEdit.LineEditEventArgs args)
    {
        var actualInput = args.Text.Split('/')[0];

        if (int.TryParse(actualInput, out var result))
        {
            result = Math.Clamp(result, ExperienceSystem.StartSkillLevel, _maxLevel);
            _skillTreeInfo.Level = result;
        }

        var resultSublevel = Math.Clamp(_skillTreeInfo.Sublevel, ExperienceSystem.StartSublevel, _maxSublevels[_skillTreeInfo.SkillTreeIndex]);
        _skillTreeInfo.Sublevel = resultSublevel;

        UpdateLineEdits();
    }

    private void OnSkillSublevelChange(LineEdit.LineEditEventArgs args)
    {
        var actualInput = args.Text.Split('/')[0];

        if (int.TryParse(actualInput, out var result))
        {
            result = Math.Clamp(result, 0, _maxSublevels[_skillTreeInfo.SkillTreeIndex]);
            _skillTreeInfo.Sublevel = result;
        }

        UpdateLineEdits();
    }
}
